### ISSUE TITLE
Error adding new land cover table

### ISSUE THREAD

**Issue by biglimp** [gusbacos/suews_database_manager#1]
Adding a new table resets the index for dlg.comboBoxSurface which then gives an error in changed_surface (typology_creator.py, line 47) since there is no surface availalbe.

**Comment by biglimp** [comment]
I commented out line 303 in typolopy_creator. This solves the issue but the new land cover does not appear until the whole plugin is restarted.

**Comment by gusbacos** [comment]
Solved in latest version
